"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Plus, RefreshCcw, BrainCircuit } from "lucide-react";

interface Security {
  id: number;
  symbol: string;
  name: string;
  exchange: string | null;
}

interface Prediction {
  predicted_score: number;
  prediction_date: string;
}

export default function SecuritiesPage() {
  const [securities, setSecurities] = useState<Security[]>([]);
  const [predictions, setPredictions] = useState<Record<number, Prediction>>({});
  const [loading, setLoading] = useState(true);

  // Form State
  const [showAdd, setShowAdd] = useState(false);
  const [symbol, setSymbol] = useState("");
  const [name, setName] = useState("");
  const [exchange, setExchange] = useState("NSE");

  const fetchData = async () => {
    try {
      const res = await api.get("/securities");
      const secs: Security[] = res.data;
      setSecurities(secs);
      
      // Fetch ML predictions in a single bulk request
      try {
        const pRes = await api.get("/securities/predictions/bulk");
        setPredictions(pRes.data);
      } catch (e) {
        console.error("Failed to fetch bulk predictions", e);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchData();
  }, []);

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await api.post("/securities", { symbol, name, exchange });
      try {
        await api.post(`/watchlist/${symbol}`);
      } catch (e) {
        console.warn("Could not auto-add to watchlist", e);
      }
      setShowAdd(false);
      setSymbol("");
      setName("");
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.detail || "Failed to register security");
    }
  };

  const triggerRefresh = async (id: number) => {
    try {
      await api.post(`/securities/${id}/refresh`);
      alert("Background Celery worker triggered to fetch latest price.");
    } catch (err) {
      console.error("Refresh failed");
    }
  };

  if (loading) return <div className="p-8">Loading...</div>;

  return (
    <div>
              <div className="mb-6 p-4 bg-yellow-900/30 border border-yellow-700/50 rounded-lg text-yellow-200 text-sm">
          <strong>⚠️ ML Disclaimer:</strong> The "Win Prob" predictions are generated by an experimental XGBoost algorithm using historical momentum. These predictions are <strong>strictly for educational purposes</strong> and do not constitute financial advice. Market dynamics are highly unpredictable. Always do your own research before investing.
        </div>
        <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-medium">Market Data</h2>
      </div>

      <div className="bg-[var(--gf-surface)] p-6 rounded-xl border border-[var(--gf-border)] mb-6 shadow-sm">
        <h3 className="text-sm font-medium mb-4 text-[var(--gf-gray-text)]">Track a new Security</h3>
        <form onSubmit={handleAdd} className="flex flex-wrap gap-4 items-end">
          <div className="flex-1 min-w-[150px]">
            <label className="block text-xs text-[var(--gf-gray-text)] mb-1">Symbol (e.g. INFY)</label>
            <input value={symbol} onChange={e => setSymbol(e.target.value)} className="w-full bg-[var(--background)] border border-[var(--gf-border)] rounded p-2 text-sm uppercase outline-none focus:border-[var(--gf-blue)]" required />
          </div>
          <div className="w-32">
            <label className="block text-xs text-[var(--gf-gray-text)] mb-1">Exchange</label>
            <select value={exchange} onChange={e => setExchange(e.target.value)} className="w-full bg-[var(--background)] border border-[var(--gf-border)] rounded p-2 text-sm outline-none focus:border-[var(--gf-blue)]">
              <option value="NSE">NSE</option>
              <option value="BSE">BSE</option>
              <option value="">US / Other</option>
            </select>
          </div>
          <div className="flex-2 min-w-[200px]">
            <label className="block text-xs text-[var(--gf-gray-text)] mb-1">Company Name</label>
            <input value={name} onChange={e => setName(e.target.value)} className="w-full bg-[var(--background)] border border-[var(--gf-border)] rounded p-2 text-sm outline-none focus:border-[var(--gf-blue)]" required />
          </div>
          <button type="submit" className="bg-[var(--gf-blue)] text-black font-medium px-6 py-2 rounded text-sm hover:opacity-90">Register Security</button>
        </form>
      </div>

      <div className="grid gap-4">
        {securities.map((sec) => (
          <div key={sec.id} className="bg-[var(--gf-surface)] p-6 rounded-xl border border-[var(--gf-border)] flex justify-between items-center">
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-medium">{sec.symbol}</h3>
                <span className="text-xs text-[var(--gf-gray-text)] px-2 py-0.5 border border-[var(--gf-border)] rounded-full">ID: {sec.id}</span>
                {sec.exchange && <span className="text-xs text-[var(--gf-gray-text)] px-2 py-0.5 border border-[var(--gf-border)] rounded-full">{sec.exchange}</span>}
              </div>
              <p className="text-sm text-[var(--gf-gray-text)]">{sec.name}</p>
            </div>
            
            <div className="flex items-center gap-8">
              {/* ML Prediction Block */}
              <div className="flex items-center gap-3">
                <BrainCircuit className="text-[var(--gf-blue)]" size={20} />
                <div className="text-right">
                  <div className="text-xs text-[var(--gf-gray-text)]">XGBoost 5-Day Outlook</div>
                  {predictions[sec.id] ? (
                    <div className={`font-medium ${predictions[sec.id].predicted_score > 0.5 ? 'text-[var(--gf-green)]' : 'text-[var(--gf-red)]'}`}>
                      {(predictions[sec.id].predicted_score * 100).toFixed(2)}% Win Prob
                    </div>
                  ) : (
                    <div className="text-sm text-[var(--gf-gray-text)]">Awaiting nightly cron...</div>
                  )}
                </div>
              </div>

              <button onClick={() => triggerRefresh(sec.id)} className="p-2 border border-[var(--gf-border)] rounded-full hover:bg-[var(--background)] transition-colors" title="Trigger Celery Worker">
                <RefreshCcw size={16} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
